server:
  port: 8181

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mysqlgcp
    username: stluser
    password: Sgh@123456

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect